Validation for adding
myma7/task-tracker pull request #5
Opened 2024-06-19 17:29 UTC by myma7

2024-06-19 20:39 UTC, micglo requested changes

2024-06-19 20:39 UTC, micglo commented on task-tracker/src/app/add-task/add-task.component.html
> +    <div *ngIf="taskService.errorMessage" class="task-error-message">
Użyj tylko samego pola 'errorMessage'. Utwórz sobie takie pole w componencie w onInit(): errorMessage = taskService.errorMessage;

2024-06-19 20:39 UTC, micglo commented on task-tracker/src/app/add-task/add-task.component.html
> +        {{ taskService.errorMessage }}
```suggestion
        {{ errorMessage }}
```

2024-06-19 20:39 UTC, micglo commented on task-tracker/src/app/add-task/add-task.component.ts
> +  constructor(public taskService: TaskService, private router: Router) {}
```suggestion
  constructor(private taskService: TaskService, private router: Router) {}
```

2024-06-19 20:39 UTC, micglo commented on task-tracker/src/app/add-task/add-task.component.ts
>    newTask: any = {
```suggestion
  newTask: Task = {
```

2024-06-19 20:39 UTC, micglo commented on task-tracker/src/app/add-task/add-task.component.ts
> +      this.taskService.errorMessage = 'Cannot add empty task or task with missing priority!';
```suggestion
      this.errorMessage = 'Cannot add empty task or task with missing priority!';
```

2024-06-19 20:39 UTC, micglo commented on task-tracker/src/app/add-task/add-task.component.ts
> +      this.taskService.errorMessage = 'You cannot add the same element! Bro, please correct it!';
```suggestion
      this.errorMessage = 'You cannot add the same element! Bro, please correct it!';
```

2024-06-19 20:39 UTC, micglo commented on task-tracker/src/app/add-task/add-task.component.ts
> +    this.taskService.errorMessage = '';
```suggestion
    this.errorMessage = ''; 
```

2024-06-19 20:39 UTC, micglo commented on task-tracker/src/app/add-task/add-task.component.ts
> +      this.router.navigate(['/add-list']);
```suggestion
```

2024-06-19 20:39 UTC, micglo commented on task-tracker/src/app/add-task/add-task.component.ts
> +      this.router.navigate(['/add-list']);
```suggestion
```

2024-06-19 20:39 UTC, micglo commented on task-tracker/src/app/confirm-dialog/confirm-dialog.component.ts
> +    <div mat-dialog-actions  style="display: flex; justify-content: flex-end;">
Wszystkie style trzymamy w .scss'ach

2024-06-19 20:39 UTC, micglo commented on task-tracker/src/app/models/task.model.ts
> +    dateCreate: string;
```suggestion
    creationDate: string;
```

2024-06-19 20:39 UTC, micglo commented on task-tracker/src/app/task-list/task-list.component.html
>              <div class="task-list__header-item">Date created</div>
```suggestion
            <div class="task-list__header-item">Creation date</div>
```

2024-06-19 20:39 UTC, micglo commented on task-tracker/src/app/task-list/task-list.component.ts
>    constructor(private taskService: TaskService, public dialog: MatDialog) { }
```suggestion
  constructor(private taskService: TaskService, private dialog: MatDialog) { }
```

2024-06-19 20:39 UTC, micglo commented on task-tracker/src/app/task-list/task-list.component.ts
> +  errorMessage: string = '';
Uzupełnij typy dla pól: tasks, filteredTasks, paginatedTasks.
Pola filteredTasks, paginatedTasks nie powinny w ogóle istnieć.

2024-06-19 20:39 UTC, micglo commented on task-tracker/src/app/task-list/task-list.component.ts
> +  loadTasks(): void {
```suggestion
  private loadTasks(): void {
```

2024-06-19 20:39 UTC, micglo commented on task-tracker/src/app/task-list/task-list.component.ts
>      this.filterTasks();
```suggestion
this.paginateTasks()
```

2024-06-19 20:39 UTC, micglo commented on task-tracker/src/app/task-list/task-list.component.ts
> +    this.filterTasks();
```suggestion
```

2024-06-19 20:39 UTC, micglo commented on task-tracker/src/app/task-list/task-list.component.html
>          <div *ngFor="let task of paginatedTasks" [class.done]="task.done" class="task-list__item task-item">
```suggestion
        <div *ngFor="let task of tasks" [class.done]="task.done" class="task-list__item task-item">
```

2024-06-19 20:39 UTC, micglo commented on task-tracker/src/app/task-list/task-list.component.ts
>      this.totalPages = Math.ceil(this.filteredTasks.length / this.itemsPerPage);
```suggestion
    this.totalPages = Math.ceil(this.tasks.length / this.itemsPerPage);
```

2024-06-19 20:39 UTC, micglo commented on task-tracker/src/app/task-list/task-list.component.ts
> -  onTaskAdded(newTask: any) {
dla metody filterTasks:
if(this.searchQuery.trim() !== '') {
this.tasks = this.tasks.filter(task => 
      task.description.toLowerCase().includes(this.searchQuery.toLowerCase())
    );
this.paginateTasks()
} else {
this.loadTasks();
}

2024-06-19 20:39 UTC, micglo commented on task-tracker/src/app/task-list/task-list.component.ts
> +  updatePagination(): void {
```suggestion
  paginateTasks(): void {
```

2024-06-19 20:39 UTC, micglo commented on task-tracker/src/app/task-list/task-list.component.ts
>      this.paginatedTasks = this.filteredTasks.slice(
```suggestion
    this.tasks = this.tasks.slice(
```

2024-06-19 20:39 UTC, micglo commented on task-tracker/src/app/task-list/task-list.component.ts
> +  onTaskAdded(newTask: any): void {
Tą metode można usunąć

2024-06-19 20:39 UTC, micglo commented on task-tracker/src/app/task-list/task-list.component.ts
> +  removeDuplicates(): void {
Do usunięcia

2024-06-19 20:39 UTC, micglo commented on task-tracker/src/app/task.service.ts
> +    public tasks: Task[] = [
```suggestion
    private tasks: Task[] = [
```

2024-06-19 20:39 UTC, micglo commented on task-tracker/src/app/task.service.ts
> +    errorMessage: string = '';
```suggestion
```

2024-06-19 20:39 UTC, micglo commented on task-tracker/src/app/task.service.ts
> +        if (this.isTaskValid(newTask)) {
Bez ifa, sprawdzenie czy task jest valid zrób w komponencie.  Metode 'isTaskValid' zrób publiczną i przed dodaniem taska uzyj tej metody w komponencie.

2024-06-19 20:39 UTC, micglo commented on task-tracker/src/app/task.service.ts
> +    sortTasksByDescriptionByAscending(): void {
Ta metoda powinna być zrobiona na poziomie komponentu

2024-06-19 20:39 UTC, micglo commented on task-tracker/src/app/task.service.ts
> +    sortTasksByDescriptionByDescending(): void {
Ta metoda powinna być zrobiona na poziomie komponentu

2024-06-20 10:53 UTC, myma7 commented on task-tracker/src/app/add-task/add-task.component.html
> +    <div *ngIf="taskService.errorMessage" class="task-error-message">
done

2024-06-20 10:55 UTC, myma7 commented on task-tracker/src/app/add-task/add-task.component.html
> +        {{ taskService.errorMessage }}
done - name commit: **fixes1**

2024-06-20 10:57 UTC, myma7 commented on task-tracker/src/app/add-task/add-task.component.ts
> +  constructor(public taskService: TaskService, private router: Router) {}
done - name commit: **fixes2**

2024-06-20 11:10 UTC, myma7 commented on task-tracker/src/app/add-task/add-task.component.ts
>    newTask: any = {
done - name commit: fixes3

2024-06-20 11:10 UTC, myma7 commented on task-tracker/src/app/add-task/add-task.component.ts
> +      this.taskService.errorMessage = 'Cannot add empty task or task with missing priority!';
done - name commit: fixes3

2024-06-20 11:10 UTC, myma7 commented on task-tracker/src/app/add-task/add-task.component.ts
> +      this.taskService.errorMessage = 'You cannot add the same element! Bro, please correct it!';
done - name commit: fixes3

2024-06-20 11:10 UTC, myma7 commented on task-tracker/src/app/add-task/add-task.component.ts
> +    this.taskService.errorMessage = '';
done - name commit: fixes3

2024-06-20 11:10 UTC, myma7 commented on task-tracker/src/app/add-task/add-task.component.ts
> +      this.router.navigate(['/add-list']);
done - name commit: fixes3

2024-06-20 11:10 UTC, myma7 commented on task-tracker/src/app/add-task/add-task.component.ts
> +      this.router.navigate(['/add-list']);
done - name commit: fixes3

2024-06-20 11:17 UTC, myma7 commented on task-tracker/src/app/confirm-dialog/confirm-dialog.component.ts
> +    <div mat-dialog-actions  style="display: flex; justify-content: flex-end;">
done - name commit: fixes4

2024-06-20 11:20 UTC, myma7 commented on task-tracker/src/app/models/task.model.ts
> +    dateCreate: string;
done - name commit: fixes5

2024-06-20 11:21 UTC, myma7 commented on task-tracker/src/app/task-list/task-list.component.html
>              <div class="task-list__header-item">Date created</div>
done - name commit: fixes5

2024-06-20 11:24 UTC, myma7 commented on task-tracker/src/app/task-list/task-list.component.ts
>    constructor(private taskService: TaskService, public dialog: MatDialog) { }
done - name commit: fixes6

2024-06-20 11:24 UTC, myma7 commented on task-tracker/src/app/task-list/task-list.component.ts
> +  loadTasks(): void {
Nie moge

2024-06-20 13:24 UTC, myma7 commented on task-tracker/src/app/task.service.ts
> +    sortTasksByDescriptionByDescending(): void {
Fixes7

2024-06-20 13:24 UTC, myma7 commented on task-tracker/src/app/task.service.ts
> +    sortTasksByDescriptionByAscending(): void {
Fixes7

2024-06-20 13:37 UTC, myma7 commented on task-tracker/src/app/task-list/task-list.component.ts
> +  removeDuplicates(): void {
Fixes8

2024-06-20 13:38 UTC, myma7 commented on task-tracker/src/app/task-list/task-list.component.ts
> +  onTaskAdded(newTask: any): void {
?

2024-06-20 21:46 UTC, merged